// <auto-generated />
namespace webnhahangasp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class updadb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updadb));
        
        string IMigrationMetadata.Id
        {
            get { return "202305041626394_upda-db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
