// <auto-generated />
namespace webnhahangasp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class deletecolnews : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletecolnews));
        
        string IMigrationMetadata.Id
        {
            get { return "202305070854230_delete-col-news"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
